spring.application.name=crucegym-app

# Configuración de la base de datos
spring.datasource.url=jdbc:mysql://localhost:3306/cruce_gym
spring.datasource.username=root
spring.datasource.password=1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuración de JPA
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect  - Ide sugiere remover
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.defer-datasource-initialization=true

# Habilitar la creación de tablas automáticamente
spring.sql.init.mode=always

# Ver mensajes detallados en la consola sobre el proceso de autenticación y redirección
logging.level.org.springframework.security=DEBUG

# Clave secreta para Remember-Me
spring.security.remember-me.key=miAplicacionSecreta123!
